version: "2"
linters:
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    paths:
    - pkg/mod$
    - vendor$
    - third_party$
    - builtin$
    - examples$
formatters:
  enable:
  - gofmt
  - goimports
  settings:
    goimports:
      local-prefixes:
      - github.com/srediag/srediag
  exclusions:
    generated: lax
    paths:
    - pkg/mod$
    - vendor$
    - third_party$
    - builtin$
    - examples$
