apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: srediags.srediag.io
spec:
  group: srediag.io
  names:
    kind: Srediag
    listKind: SrediagList
    plural: srediags
    singular: srediag
    shortNames:
      - srd
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - version
                - config
              properties:
                version:
                  type: string
                  description: "SREDIAG image version"
                config:
                  type: object
                  required:
                    - opentelemetry
                  properties:
                    opentelemetry:
                      type: object
                      required:
                        - endpoint
                      properties:
                        endpoint:
                          type: string
                          description: "OTLP collector endpoint"
                        protocol:
                          type: string
                          enum: ["grpc", "http"]
                          default: "grpc"
                        tls:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                            secretName:
                              type: string
                    security:
                      type: object
                      properties:
                        tls:
                          type: object
                          properties:
                            enabled:
                              type: boolean
                            secretName:
                              type: string
                        auth:
                          type: object
                          required:
                            - type
                            - secretName
                          properties:
                            type:
                              type: string
                              enum: ["token", "basic", "oauth"]
                            secretName:
                              type: string
                plugins:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - type
                      - version
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                      version:
                        type: string
                      config:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: "^[0-9]+m?$"
                        memory:
                          type: string
                          pattern: "^[0-9]+(Ki|Mi|Gi|Ti|Pi|Ei)?$"
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                          pattern: "^[0-9]+m?$"
                        memory:
                          type: string
                          pattern: "^[0-9]+(Ki|Mi|Gi|Ti|Pi|Ei)?$"
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Running
                    - Failed
                    - Succeeded
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      observedGeneration:
                        type: integer
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                installedPlugins:
                  type: array
                  items:
                    type: string
                lastUpdated:
                  type: string
                  format: date-time
      subresources:
        status: {}
