gcp:
  project_id: your-project-id
  zone: us-central1-a
  region: us-central1
  
  credentials:
    type: service_account
    file: /path/to/service-account.json
    use_workload_identity: false
  
  monitoring:
    interval: 60s
    enhanced: true
    metrics:
      - compute.googleapis.com/instance/cpu/utilization
      - compute.googleapis.com/instance/memory/usage
      - compute.googleapis.com/instance/disk/read_bytes_count
      - compute.googleapis.com/instance/disk/write_bytes_count
      - compute.googleapis.com/instance/network/received_bytes_count
      - compute.googleapis.com/instance/network/sent_bytes_count
    
    custom_metrics:
      - name: application_errors
        type: custom.googleapis.com/application/errors
        labels:
          - service
          - environment
    
    alerts:
      - name: high_cpu_usage
        metric: compute.googleapis.com/instance/cpu/utilization
        threshold: 0.8
        duration: 300s
        severity: WARNING
  
  opentelemetry:
    endpoint: localhost:4317
    protocol: grpc
    sampling:
      type: probabilistic
      ratio: 0.1
    
  services:
    compute_engine:
      enabled: true
      labels:
        environment: production
    
    gke:
      enabled: true
      clusters:
        - name: production
          location: us-central1
    
    cloud_functions:
      enabled: true
      functions:
        - name: api-handler
          region: us-central1
    
  integrations:
    cloud_monitoring:
      enabled: true
      workspace: production
    
    cloud_trace:
      enabled: true
      sampling_rate: 0.1
    
    cloud_logging:
      enabled: true
      log_buckets:
        - name: production-logs
          retention_days: 30
          filters:
            - resource.type="gce_instance"
            - resource.type="k8s_container" 
