receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "${OTEL_GRPC_ENDPOINT:-0.0.0.0:4317}"
        tls:
          cert_file: "${OTEL_GRPC_TLS_CERT:-}"
          key_file: "${OTEL_GRPC_TLS_KEY:-}"
      http:
        endpoint: "${OTEL_HTTP_ENDPOINT:-0.0.0.0:4318}"
        tls:
          cert_file: "${OTEL_HTTP_TLS_CERT:-}"
          key_file: "${OTEL_HTTP_TLS_KEY:-}"
  hostmetrics:
    collection_interval: "${HOSTMETRICS_INTERVAL:-10s}"
    scrapers:
      cpu:
        metrics:
          system.cpu.time:
            enabled: true
          system.cpu.utilization:
            enabled: true
      disk:
        metrics:
          system.disk.operations:
            enabled: true
          system.disk.io:
            enabled: true
      filesystem:
        metrics:
          system.filesystem.usage:
            enabled: true
          system.filesystem.utilization:
            enabled: true
      memory:
        metrics:
          system.memory.usage:
            enabled: true
          system.memory.utilization:
            enabled: true
      network:
        metrics:
          system.network.connections:
            enabled: true
          system.network.io:
            enabled: true
      process:
        metrics:
          process.cpu.time:
            enabled: true
          process.memory.usage:
            enabled: true

processors:
  batch:
    timeout: "${BATCH_TIMEOUT:-1s}"
    send_batch_size: "${BATCH_SIZE:-1024}"
    send_batch_max_size: "${BATCH_MAX_SIZE:-2048}"
  
  memory_limiter:
    check_interval: "${MEMORY_CHECK_INTERVAL:-1s}"
    limit_mib: "${MEMORY_LIMIT_MIB:-1024}"
    spike_limit_mib: "${MEMORY_SPIKE_LIMIT_MIB:-128}"
    
  resourcedetection:
    detectors: [env, system, docker, kubernetes]
    timeout: "${RESOURCE_DETECTION_TIMEOUT:-2s}"
    override: true
    
  k8sattributes:
    auth_type: "serviceAccount"
    extract:
      metadata:
        - k8s.pod.name
        - k8s.pod.uid
        - k8s.deployment.name
        - k8s.namespace.name
        - k8s.node.name
        - k8s.container.name
    filter:
      node_from_env_var: "K8S_NODE_NAME"

exporters:
  otlp:
    endpoint: "${OTLP_ENDPOINT:-localhost:4317}"
    tls:
      insecure: "${OTLP_INSECURE:-false}"
      ca_file: "${OTLP_CA_FILE:-}"
      cert_file: "${OTLP_CERT_FILE:-}"
      key_file: "${OTLP_KEY_FILE:-}"
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 5000
      
  prometheus:
    endpoint: "${PROMETHEUS_ENDPOINT:-0.0.0.0:9090}"
    namespace: "srediag"
    const_labels:
      deployment_environment: "${DEPLOYMENT_ENV:-production}"
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

extensions:
  health_check:
    endpoint: "${HEALTH_CHECK_ENDPOINT:-0.0.0.0:13133}"
  pprof:
    endpoint: "${PPROF_ENDPOINT:-0.0.0.0:1777}"
  zpages:
    endpoint: "${ZPAGES_ENDPOINT:-0.0.0.0:55679}"

service:
  telemetry:
    logs:
      level: "${LOG_LEVEL:-info}"
      development: false
      encoding: json
    metrics:
      level: detailed
      address: "${METRICS_ADDRESS:-0.0.0.0:8888}"
  
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, k8sattributes, resourcedetection, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [memory_limiter, k8sattributes, resourcedetection, batch]
      exporters: [otlp, prometheus] 
 