# SREDIAG Builder Configuration
# This file defines the components to be built as plugins

dist:
  name: srediag
  description: "SRE Diagnostics Collector"
  version: "0.1.0"
  output_path: ./bin/srediag

# Core components that will be built as plugins
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.124.0
  - gomod: go.opentelemetry.io/collector/receiver/nopreceiver v0.124.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.124.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.124.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.124.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.124.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.124.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.124.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.30.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v0.124.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.30.0

