# OTel Collector Pipeline Configuration for SREDIAG (test defaults)

receivers:
  otlp: !include plugins.d/receivers/otlp@service.yaml
  nop:  !include plugins.d/receivers/nop@service.yaml

processors:
  batch:           !include plugins.d/processors/batch@service.yaml
  k8sattributes:   !include plugins.d/processors/k8sattributes@service.yaml
  memory_limiter:  !include plugins.d/processors/memory_limiter@service.yaml
  resourcedetection: !include plugins.d/processors/resourcedetection@service.yaml

exporters:
  debug:      !include plugins.d/exporters/debug@service.yaml
  otlp:       !include plugins.d/exporters/otlp@service.yaml
  otlphttp:   !include plugins.d/exporters/otlphttp@service.yaml
  prometheus: !include plugins.d/exporters/prometheus@service.yaml

extensions:
  health_check: !include plugins.d/extensions/health_check@service.yaml
  pprof:        !include plugins.d/extensions/pprof@service.yaml
  zpages:       !include plugins.d/extensions/zpages@service.yaml

service:
  telemetry:
    logs:
      level: debug
      development: true
      encoding: json
    metrics:
      level: detailed
      address: 0.0.0.0:8888
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp, nop]
      processors: [memory_limiter, k8sattributes, resourcedetection, batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp, nop]
      processors: [memory_limiter, k8sattributes, resourcedetection, batch]
      exporters: [debug, otlp, prometheus]
    logs:
      receivers: [otlp, nop]
      processors: [memory_limiter, k8sattributes, resourcedetection, batch]
      exporters: [debug, otlp] 
 