# SREDIAG Configuration
version: "v0.1.0"

# Service settings
service:
  name: "srediag"
  environment: "${SREDIAG_ENV:-production}"
  port: "${SREDIAG_PORT:-8080}"

# Collector settings
collector:
  enabled: true
  config_path: "configs/otel-config.yaml"
  memory_limit_mib: 1024
  cpu_limit_cores: 2

# Application logging
logging:
  level: "${LOG_LEVEL:-info}"
  format: "${LOG_FORMAT:-json}"
  file:
    enabled: "${LOG_FILE_ENABLED:-false}"
    path: "${LOG_FILE_PATH:-/var/log/srediag/srediag.log}"
