plugins:
  path: ./bin/plugins

receivers:
  nop:
    # No configuration needed for nop receiver

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1024

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: localhost:4317
    tls:
      insecure: true
  otlphttp:
    endpoint: http://localhost:4318

extensions:
  zpages:
    endpoint: localhost:55679

service:
  extensions: [zpages]
  pipelines:
    traces:
      receivers: [nop]
      processors: [batch, memory_limiter]
      exporters: [debug, otlp, otlphttp] 
