auth_type: "serviceAccount"
extract:
  metadata:
    - k8s.pod.name
    - k8s.pod.uid
    - k8s.deployment.name
    - k8s.namespace.name
    - k8s.node.name
    - k8s.container.name
filter:
  node_from_env_var: "K8S_NODE_NAME" 
