name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go 1.24
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Install tools
        run: |
          go install github.com/magefile/mage@latest
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest

      - name: Run tasks
        run: mage
